export const pagePath = {
  ONBOARDING: "onboarding",
  LOGIN: "login",
  REGISTER: "register",
  HOME: "home",
  AICHAT: "aichat",
  ARTICLE: "article",
  ARTICLEEDIT: 'article_edit',
  ARTICLECREATE: 'article_create',
  MYPAGE: "mypage",
  OAUTH_CALLBACK_KAKAO: "/oauth/callback/kakao",
  MOVIE_DETAIL: "/movies/:id",
  MY_INTERPRETATIONS: "/mypage/interpretations",
  MY_NICKNAME: "/mypage/nickname",
  CREATE_INTERPRETATION: "/movies/:id/interpretation/new",
  EDIT_INTERPRETATION: "/interpretation/edit/:id",
};
